import 'dart:io';

import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/report_chart_data.dart';
import 'app_repositories.dart';
import 'report_chart_service.dart';
import 'reports_service.dart';
import 'user_preferences.dart';

class PdfExportService {
  const PdfExportService({
    ReportsService? reportsService,
    ReportChartService? chartService,
  })  : _reportsService = reportsService ?? const ReportsService(),
        _chartService = chartService ?? const ReportChartService();

  final ReportsService _reportsService;
  final ReportChartService _chartService;

  Future<File> exportFarmReport({
    required AppRepositories repositories,
    required UserPreferences userPreferences,
  }) async {
    final summary = await _reportsService.load(
      repositories: repositories,
      userPreferences: userPreferences,
    );
    final charts = await _chartService.load(repositories);
    final currency = NumberFormat.simpleCurrency(name: 'KES', decimalDigits: 0);
    final dateFormat = DateFormat('d MMM yyyy, HH:mm');

    final doc = pw.Document();
    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Text(
            summary.orgName,
            style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            'Kalro Sericulture farm report · ${dateFormat.format(summary.generatedAt)}',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
          ),
          pw.SizedBox(height: 20),
          pw.Text('Overview', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          _metricTable([
            ['Active batches', '${summary.activeBatches}'],
            ['Total larvae', '${summary.bombyxLarvae + summary.eriLarvae}'],
            ['Average survival', '${summary.averageSurvivalPercent.toStringAsFixed(0)}%'],
            ['Total mortality', '${summary.totalMortality}'],
            ['Feed logged', _formatGrams(summary.totalFeedGrams)],
            ['Harvest weight', _formatGrams(summary.totalHarvestWeightGrams)],
            ['Pending receivable', currency.format(summary.totalReceivable)],
            ['Pending payable', currency.format(summary.totalPayable)],
          ]),
          pw.SizedBox(height: 16),
          pw.Text('Batch comparison', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          _batchTable(charts),
          pw.SizedBox(height: 16),
          pw.Text(
            'Generated by Kalro Sericulture',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ],
      ),
    );

    final directory = await getApplicationDocumentsDirectory();
    final exportsDir = Directory('${directory.path}/kalro_exports');
    if (!await exportsDir.exists()) {
      await exportsDir.create(recursive: true);
    }

    final timestamp = DateFormat('yyyyMMdd_HHmmss').format(DateTime.now());
    final file = File('${exportsDir.path}/kalro_report_$timestamp.pdf');
    await file.writeAsBytes(await doc.save());
    return file;
  }

  pw.Widget _metricTable(List<List<String>> rows) {
    return pw.TableHelper.fromTextArray(
      headers: ['Metric', 'Value'],
      data: rows,
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
      cellAlignment: pw.Alignment.centerLeft,
      columnWidths: {0: const pw.FlexColumnWidth(2), 1: const pw.FlexColumnWidth(1.5)},
    );
  }

  pw.Widget _batchTable(ReportChartData charts) {
    if (charts.batchComparisons.isEmpty) {
      return pw.Text('No active batches.');
    }

    return pw.TableHelper.fromTextArray(
      headers: ['Species', 'Started', 'Live', 'Survival', 'Feed', 'Harvest', 'Status'],
      data: charts.batchComparisons
          .map(
            (row) => [
              row.speciesLabel,
              row.startDateLabel,
              '${row.liveCount}/${row.startingCount}',
              '${row.survivalPercent.toStringAsFixed(0)}%',
              _formatGrams(row.totalFeedGrams),
              row.harvestWeightGrams > 0 ? _formatGrams(row.harvestWeightGrams) : '—',
              row.statusLabel,
            ],
          )
          .toList(),
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9),
      cellStyle: const pw.TextStyle(fontSize: 9),
      cellAlignment: pw.Alignment.centerLeft,
    );
  }

  String _formatGrams(double grams) {
    if (grams >= 1000) return '${(grams / 1000).toStringAsFixed(1)} kg';
    return '${grams.round()} g';
  }
}
