#!/usr/bin/env python3
"""Generate lib/l10n/sw_messages.dart from the English→Swahili dictionary."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "lib/l10n/sw_messages.dart"

# Exact UI + domain phrases. Keep keys identical to English source strings.
MESSAGES = {
    # Nav / chrome
    "Today": "Leo",
    "Batches": "Makundi",
    "Plan": "Panga",
    "Farm": "Shamba",
    "You": "Wewe",
    "Home": "Nyumbani",
    "Profile": "Profaili",
    "Settings": "Mipangilio",
    "Help": "Msaada",
    "Skip": "Ruka",
    "Next": "Endelea",
    "Back": "Rudi",
    "Cancel": "Ghairi",
    "Save": "Hifadhi",
    "Delete": "Futa",
    "Edit": "Hariri",
    "Add": "Ongeza",
    "Create": "Unda",
    "Retry": "Jaribu tena",
    "Remove": "Ondoa",
    "Replace": "Badilisha",
    "Download": "Pakua",
    "Restore": "Rejesha",
    "Sign out": "Toka",
    "Loading...": "Inapakia...",
    "OK": "Sawa",
    "None": "Hakuna",
    "Active": "Hai",
    "Closed": "Yamefungwa",
    "Status": "Hali",
    "Records": "Rekodi",
    "Timeline": "Ratiba",
    "Overview": "Muhtasari",
    "Language": "Lugha",
    "English": "Kiingereza",
    "Swahili": "Kiswahili",
    "Date": "Tarehe",
    "Species": "Aina",
    "Started": "Imeanza",
    "Live": "Hai",
    "Feed": "Chakula",
    "Harvest": "Mavuno",
    "Harvested": "Yamevunwa",
    "Mortality": "Vifo",
    "Environment": "Mazingira",
    "House": "Nyumba",
    "Deaths": "Vifo",
    "Alerts": "Arifa",
    "Reports": "Ripoti",
    "Reminders": "Vikumbusho",
    "Finance": "Fedha",
    "Payments": "Malipo",
    "Purchases": "Manunuzi",
    "Inventory": "Mali",
    "Field guide": "Mwongozo wa shamba",
    "Analytics": "Takwimu",
    "Support": "Msaada",
    "Users": "Watumiaji",
    "Organization": "Shirika",
    "Username": "Jina la kuingia",
    "PIN": "PIN",
    "Login name": "Jina la kuingia",
    "Your name": "Jina lako",
    "Farm / organization": "Shamba / shirika",
    "Confirm PIN": "Thibitisha PIN",
    "PIN (4+ digits)": "PIN (tarakimu 4+)",
    "Your role": "Wajibu wako",
    "Get started": "Anza",
    "Setting up...": "Inaandaa...",
    "Saving...": "Inahifadhi...",
    "Working...": "Inafanya kazi...",
    "Exporting PDF...": "Inatengeneza PDF...",
    # Roles
    "Silkworm Rearer": "Mfugaji wa minyoo hariri",
    "Adopted Seed Rearer": "Mfugaji wa Mbegu Aliyepitishwa",
    "Registered Seed Producer": "Mzalishaji wa Mbegu Aliyesajiliwa",
    "Rearing Support Unit": "Kitengo cha Msaada wa Ufugaji",
    "Admin": "Msimamizi",
    "Caretaker": "Mhudumu",
    "Viewer": "Mtaazamaji",
    "Full access including team management, backups, and cloud sync.": "Ufikiaji kamili: timu, nakala, na wingu.",
    "Can record batches, logs, payments, and purchases. Cannot manage users.": "Anaweza kurekodi makundi, chakula, malipo na manunuzi. Hawezi kusimamia watumiaji.",
    "Read-only access to farm data and reports.": "Kusoma tu: data na ripoti za shamba.",
    # Species / status
    "Eri": "Eri",
    "Bombyx": "Bombyx",
    "Bombyx mori": "Bombyx mori",
    "Samia ricini": "Samia ricini",
    "Mulberry": "Mforosadi",
    "Castor / kesseru": "Mbarika / kesseru",
    "Mounting": "Kupandisha",
    "Cocooning": "Kufuka",
    "Closed": "Yamefungwa",
    "Pending": "Yanasubiri",
    "Settled": "Yamemalizwa",
    "Receivable": "Yanayopokelewa",
    "Payable": "Yanayolipwa",
    # Lifecycle
    "Hatch": "Kutotoa",
    "Instar": "Kipindi cha mabuu",
    "Moult": "Kuvua ngozi",
    "Spinning": "Kusokota",
    "Cocoon harvest": "Mavuno ya vifukofuko",
    "Moth emergence": "Kutoka kwa nondo",
    "Egg incubation": "Kuluza mayai",
    "Egg hatch": "Kutotoa mayai",
    "1st instar": "Kipindi cha 1",
    "2nd instar": "Kipindi cha 2",
    "3rd instar": "Kipindi cha 3",
    "4th instar": "Kipindi cha 4",
    "5th instar": "Kipindi cha 5",
    "1st moult": "Kuvua 1",
    "2nd moult": "Kuvua 2",
    "3rd moult": "Kuvua 3",
    "4th moult": "Kuvua 4",
    "Moths emerge": "Nondo wanatoka",
    "Hatching & brushing": "Kutotoa na kuhamisha",
    "Typical": "Kawaida",
    "Predicted": "Inayotarajiwa",
    "Shift": "Mabadiliko",
    "Recorded": "Imerekodiwa",
    "Cool / wet": "Baridi / maji",
    "Hot / dry": "Joto / kavu",
    "Short on leaf": "Majani machache",
    "Plenty of leaf": "Majani ya kutosha",
    "Missed feeds": "Siku bila chakula",
    "Ideal temperature, humidity, and enough leaf": "Joto, unyevu, na majani vya kutosha",
    "Cool air and high humidity slow growth": "Hewa baridi na unyevu mwingi huchelewesha ukuaji",
    "Heat and dry air stress larvae and cocoons": "Joto na hewa kavu inasisitiza mabuu na vifukofuko",
    "Underfeeding stretches instars": "Chakula kidogo kinarefusha vipindi",
    "Full feeding keeps late instars close to typical": "Chakula cha kutosha kinashikilia ratiba",
    "A few days without enough leaf this week": "Siku chache bila majani ya kutosha wiki hii",
    # Today plan / feed
    "No leaf yet — eggs are still incubating": "Bado hakuna majani — mayai bado yanaluzwa",
    "Stop feeding — moult rest day": "Acha kulisha — siku ya kuvua",
    "Stop feeding — move worms to mountages": "Acha kulisha — hamisha kwenye mountages",
    "No feeding today": "Hakuna chakula leo",
    "Harvest window": "Dirisha la mavuno",
    "Stop feeding today": "Acha kulisha leo",
    "Light morning feed": "Chakula kidogo asubuhi",
    "Pre-moult check": "Angalia kabla ya kuvua",
    "Mountages today": "Mountages leo",
    "Feed today": "Chakula leo",
    "Check the batch and mark the stage when you see it.": "Angalia kundi na weka alama unapoona hatua.",
    "Check the batch and mark the stage when you observe it.": "Angalia kundi na weka alama unapoona hatua.",
    "Rest day": "Siku ya pumziko",
    "Rest": "Pumziko",
    "Today’s work": "Kazi ya leo",
    "Today's work": "Kazi ya leo",
    "DAY": "SIKU",
    "day": "siku",
    "larvae": "mabuu",
    "No feed": "Hakuna chakula",
    "I see moult": "Naona kuvua",
    "Mark stage": "Weka hatua",
    "Mark": "Weka",
    "Update": "Sasisha",
    "Observed": "Imeonekana",
    # House
    "House now": "Nyumba sasa",
    "House OK": "Nyumba sawa",
    "Cool and dry": "Baridi na kavu",
    "Hot and wet": "Joto na maji",
    "Too cool": "Baridi mno",
    "Too hot": "Joto mno",
    "Too dry": "Kavu mno",
    "Too wet": "Maji mengi",
    "Temperature": "Joto",
    "Air": "Hewa",
    "Dry": "Kavu",
    "Wet": "Maji",
    "Humidity OK": "Unyevu sawa",
    "Save house": "Hifadhi nyumba",
    "Three taps. This moves hatch and harvest on Plan.": "Gusa mara tatu. Hii inahamisha kutotoa na mavuno kwenye Panga.",
    "House logged — Plan dates will shift if it stays like this.": "Nyumba imerekodiwa — tarehe za Panga zitahama ikidumu hivi.",
    "Log deaths": "Rekodi vifo",
    "Disease (optional)": "Ugonjwa (si lazima)",
    "None / not sure": "Hakuna / sija hakika",
    "Photo (optional)": "Picha (si lazima)",
    "Photo attached": "Picha imeambatishwa",
    "Seed-lot risk": "Hatari ya mbegu",
    "Seed-lot risk — isolate and tell CRC.": "Hatari ya mbegu — tenga na mwambie CRC.",
    "Seed-lot risk — isolate and tell CRC. Do not use moths for eggs.": "Hatari ya mbegu — tenga na mwambie CRC. Usitumie nondo kwa mayai.",
    "Rest day — no leaf to log": "Siku ya pumziko — hakuna majani ya kurekodi",
    "Suggested ration": "Kiasi kilichopendekezwa",
    "Light morning then full (Eri day 1)": "Kidogo asubuhi kisha kamili (Eri siku 1)",
    # Screens
    "Kalro Sericulture": "Kalro Ufugaji wa Hariri",
    "Eri & Bombyx mori rearing management": "Usimamizi wa ufugaji wa Eri na Bombyx mori",
    "Set up your farm profile": "Andaa profaili ya shamba",
    "Create your farm, then we will show you the five tabs: Today, Batches, Plan, Farm, and You.": "Unda shamba, kisha tutakuonyesha vichupo vitano: Leo, Makundi, Panga, Shamba, na Wewe.",
    "Please choose your role": "Tafadhali chagua wajibu wako",
    "PIN must be at least 4 digits": "PIN iwe angalau tarakimu 4",
    "PINs do not match": "PIN hazifanani",
    "Sign in with the login name and PIN you set for this farm.": "Ingia kwa jina na PIN ulizoweka kwa shamba hili.",
    "Enter your username": "Weka jina la kuingia",
    "Setup required": "Usanidi unahitajika",
    "Complete app setup first.": "Kamilisha usanidi wa programu kwanza.",
    "Sign In": "Ingia",
    "Signing in...": "Inaingia...",
    "Could not prepare farm account:": "Haikuweza kuandaa akaunti ya shamba:",
    "Batch Details": "Maelezo ya kundi",
    "Batch not found": "Kundi halijapatikana",
    "New Batch": "Kundi jipya",
    "Start date": "Tarehe ya kuanza",
    "Egg start date": "Tarehe ya mayai",
    "Select batch": "Chagua kundi",
    "Source": "Chanzo",
    "Strain": "Aina ya mbegu",
    "Location": "Mahali",
    "Current stage": "Hatua ya sasa",
    "Live larvae": "Mabuu hai",
    "Live Larvae": "Mabuu hai",
    "Update status": "Sasisha hali",
    "Lifecycle timeline": "Ratiba ya mzunguko",
    "Lifecycle planner": "Mpango wa mzunguko",
    "Lifecycle plan": "Mpango wa mzunguko",
    "My batches": "Makundi yangu",
    "Plan a cycle": "Panga mzunguko",
    "Start this batch": "Anza kundi hili",
    "Full predicted timeline": "Ratiba kamili iliyotabiriwa",
    "What to prepare": "Nini uandae",
    "No predicted dates yet": "Bado hakuna tarehe zilizotabiriwa",
    "Dates move with temperature, humidity, and how much leaf you log. Mark a stage when you see it.": "Tarehe zinahama na joto, unyevu, na majani unayorekodi. Weka hatua unapoiona.",
    "What if weather or leaf changes?": "Je hali ya hewa au majani yakibadilika?",
    "What if conditions change?": "Je hali ikibadilika?",
    "How dates change": "Jinsi tarehe zinavyobadilika",
    "Pre-moult signs": "Ishara kabla ya kuvua",
    "Ready to spin?": "Tayari kusokota?",
    "Ready to spin (Bombyx)": "Tayari kusokota (Bombyx)",
    "I see this — mark today": "Naona hivi — weka leo",
    "Today’s rearing plan": "Mpango wa ufugaji wa leo",
    "Today's rearing plan": "Mpango wa ufugaji wa leo",
    "Feed, rest days, and harvest from the KALRO calendars — tap to log work.": "Chakula, siku za pumziko, na mavuno kutoka kalenda za KALRO — gusa kurekodi kazi.",
    "Needs attention": "Inahitaji uangalizi",
    "Needs Attention": "Inahitaji uangalizi",
    "in progress": "vinaendelea",
    "Leaf short for today": "Majani hayatoshi leo",
    "Leaf for today": "Majani ya leo",
    "Start in three steps": "Anza kwa hatua tatu",
    "The bottom bar is Today · Batches · Plan · Farm · You. Nothing important is in a hidden menu.": "Mwambaa chini ni Leo · Makundi · Panga · Shamba · Wewe. Hakuna kilicho muhimu kwenye menyu iliyofichwa.",
    "Plan hatch and harvest": "Panga kutotoa na mavuno",
    "Open the Plan tab and pick a start date.": "Fungua Panga na chagua tarehe ya kuanza.",
    "Start a batch of eggs": "Anza kundi la mayai",
    "Batches tab, or the + button.": "Kichupo cha Makundi, au kitufe cha +.",
    "Log feed and deaths": "Rekodi chakula na vifo",
    "Farm tab, or Feed on this screen.": "Kichupo cha Shamba, au Chakula kwenye skrini hii.",
    "Open Plan": "Fungua Panga",
    "Quick add": "Ongeza haraka",
    "Quick Add": "Ongeza haraka",
    "Start new batch": "Anza kundi jipya",
    "Start New Batch": "Anza kundi jipya",
    "Eggs in — calendar starts": "Mayai ndani — kalenda inaanza",
    "Log feeding": "Rekodi chakula",
    "Log Feeding": "Rekodi chakula",
    "Opens the Feeding page": "Inafungua ukurasa wa Chakula",
    "Record health & mortality": "Rekodi afya na vifo",
    "Record Health & Mortality": "Rekodi afya na vifo",
    "Opens the Health page": "Inafungua ukurasa wa Afya",
    "Or use the Farm tab for the full feeding, health, and harvest pages.": "Au tumia Shamba kwa kurasa kamili za chakula, afya, na mavuno.",
    "Log work, leaf, money, and the field guide.": "Rekodi kazi, majani, fedha, na mwongozo.",
    "Daily records": "Rekodi za kila siku",
    "These used to be hidden in the menu. Use them every day.": "Hizi zilikuwa kwenye menyu. Zitumie kila siku.",
    "Feeding": "Chakula",
    "Leaf grams for live larvae": "Gramu za majani kwa mabuu hai",
    "Health & mortality": "Afya na vifo",
    "Health & Mortality": "Afya na vifo",
    "Deaths, disease, live count": "Vifo, magonjwa, idadi hai",
    "Cocoon Harvest": "Mavuno ya vifukofuko",
    "Count, weight, and the harvest window": "Idadi, uzito, na dirisha la mavuno",
    "Leaf, money & guides": "Majani, fedha na miongozo",
    "Leaf & stock": "Majani na hisa",
    "Mulberry, castor, kesseru vs need": "Mforosadi, mbarika, kesseru dhidi ya mahitaji",
    "Mulberry, castor, kesseru vs need to harvest": "Mforosadi, mbarika, kesseru hadi mavuno",
    "KALRO hatch, moult rest, spinning signs": "KALRO: kutotoa, kuvua, ishara za kusokota",
    "Payments and farm money": "Malipo na fedha za shamba",
    "Payments, receivables, and seed purchases.": "Malipo, mapato, na manunuzi ya mbegu.",
    "Cycle, feed, and harvest summaries": "Muhtasari wa mzunguko, chakula, na mavuno",
    "No batches yet": "Hakuna makundi bado",
    "From live vs eggs": "Kutoka hai dhidi ya mayai",
    "Logged so far": "Iliyorekodiwa hadi sasa",
    "Harvest window open": "Dirisha la mavuno limefunguka",
    "On track": "Iko sawa",
    "Watch mortality": "Angalia vifo",
    "Good morning": "Habari za asubuhi",
    "Good afternoon": "Habari za mchana",
    "Good evening": "Habari za jioni",
    "Next up": "Kinachofuata",
    "Today's tasks": "Kazi za leo",
    "Today’s tasks": "Kazi za leo",
    "No active batches": "Hakuna makundi hai",
    "No active batches yet": "Hakuna makundi yanayoendelea",
    "Start a rearing cycle to plan milestones and record daily work.": "Anzisha mzunguko kupanga hatua na kurekodi kazi ya kila siku.",
    "Start a rearing batch to track lifecycle dates.": "Anzisha kundi ili kufuatilia mizunguko.",
    "Create batch": "Unda kundi",
    "Active batches": "Makundi yanayoendelea",
    "Active Batches": "Makundi yanayoendelea",
    "Closed batches": "Makundi yaliyofungwa",
    "archived": "yaliyohifadhiwa",
    "All Batches": "Makundi yote",
    "Create cycles and log feeding, health, and harvest.": "Unda mizunguko na rekodi chakula, afya, na mavuno.",
    "Start a batch, or plan a cycle to see hatch, spinning, harvest, and moth dates.": "Anza kundi, au panga mzunguko kuona kutotoa, kusokota, mavuno, na nondo.",
    "Pick species and start date, then test weather and leaf scenarios before you start eggs.": "Chagua aina na tarehe, kisha jaribu hali ya hewa na majani kabla ya kuanza mayai.",
    "See hatch, harvest, and moth dates. Test cool weather, heat, or short leaf.": "Ona kutotoa, mavuno, na nondo. Jaribu baridi, joto, au majani machache.",
    "Dates use logged weather and feeding when you have records. Cool or dry houses, short leaf, and missed feeds each move hatch, harvest, and moths differently.": "Tarehe zinatumia joto na chakula ulichorekodi. Nyumba baridi au kavu, majani machache, na siku bila chakula zinahamisha tarehe tofauti.",
    "Same as a typical house with enough leaf.": "Kama nyumba ya kawaida yenye majani ya kutosha.",
    "Logged conditions affecting dates": "Hali iliyorekodiwa inayoathiri tarehe",
    "How this scenario moves dates": "Jinsi hali hii inavyohamisha tarehe",
    "Weather and feeding look typical — dates follow the standard cycle.": "Hali na chakula ni vya kawaida — tarehe zinafuata mzunguko wa kawaida.",
    "Dates use typical durations. Log temperature, humidity, and feeding to refine them, or try a scenario.": "Tarehe ni za kawaida. Rekodi joto, unyevu, na chakula ili kurekebisha, au jaribu hali.",
    # Walkthrough
    "Open the app here each morning. You will see what to feed, when to rest the worms, and when harvest is due.": "Fungua hapa kila asubuhi. Utaona cha kulisha, lini kupumzisha, na lini mavuno.",
    "Bottom tab: Today": "Kichupo: Leo",
    "A batch is one lot of eggs. Start a cycle here, then tap it to log feed, deaths, and harvest on that batch.": "Kundi ni lundo la mayai. Anza mzunguko hapa, kisha gusa kurekodi chakula, vifo, na mavuno.",
    "Bottom tab: Batches": "Kichupo: Makundi",
    "See hatch, moult rest days, spinning, and the cocoon harvest window before you start eggs. Weather and leaf will move the dates.": "Ona kutotoa, siku za kuvua, kusokota, na dirisha la mavuno kabla ya kuanza mayai. Hewa na majani zinahamisha tarehe.",
    "Bottom tab: Plan": "Kichupo: Panga",
    "Log feeding, health, and harvest. Check leaf stock, money, reports, and the KALRO field guide — nothing is hidden in a side menu.": "Rekodi chakula, afya, na mavuno. Angalia majani, fedha, ripoti, na mwongozo — hakuna kilichofichwa kando.",
    "Bottom tab: Farm": "Kichupo: Shamba",
    "Open the farm": "Fungua shamba",
    # Feeding / health / harvest forms
    "Feed type": "Aina ya chakula",
    "Quantity (grams)": "Kiasi (gramu)",
    "Feeding stage (optional)": "Hatua ya chakula (si lazima)",
    "Notes (optional)": "Maelezo (si lazima)",
    "Save feeding log": "Hifadhi chakula",
    "Feeding logs": "Rekodi za chakula",
    "No feedings yet": "Hakuna chakula bado",
    "Log each feeding to track leaf use and consumption over the cycle.": "Rekodi kila mlo kufuatilia matumizi ya majani.",
    "Total feed": "Chakula jumla",
    "Entries": "Nyingizo",
    "Latest": "Karibuni",
    "Log mortality": "Rekodi vifo",
    "Count": "Idadi",
    "Reason (optional)": "Sababu (si lazima)",
    "Treatment (optional)": "Matibabu (si lazima)",
    "Save mortality log": "Hifadhi vifo",
    "Mortality logs": "Rekodi za vifo",
    "No mortality logged": "Hakuna vifo bado",
    "Record daily checks to track larvae health and spot problems early.": "Rekodi ukaguzi wa kila siku kufuatilia afya ya mabuu.",
    "Total lost": "Jumla iliyopotea",
    "Last check": "Ukaguzi wa mwisho",
    "Daily check": "Ukaguzi wa kila siku",
    "Log environment": "Rekodi mazingira",
    "Temperature (°C)": "Joto (°C)",
    "Humidity (%)": "Unyevu (%)",
    "Save reading": "Hifadhi vipimo",
    "No readings yet": "Hakuna vipimo bado",
    "Log temperature and humidity daily to catch stress before it affects larvae.": "Rekodi joto na unyevu kila siku kabla hali haijaharibu mabuu.",
    "Log reading": "Rekodi kipimo",
    "Latest temp": "Joto la karibuni",
    "Latest RH": "Unyevu wa karibuni",
    "Out of range": "Nje ya kiwango",
    "Within range": "Ndani ya kiwango",
    "Record cocoon harvest": "Rekodi mavuno ya vifukofuko",
    "Cocoon count": "Idadi ya vifukofuko",
    "Total weight (grams)": "Uzito jumla (gramu)",
    "Defective count": "Idadi yenye kasoro",
    "Shell weight sample (g, optional)": "Sampuli ya ganda (g, si lazima)",
    "Save harvest": "Hifadhi mavuno",
    "No harvest recorded": "Hakuna mavuno yaliyorekodiwa",
    "Weigh cocoons when ready to track yield, survival, and quality.": "Pima vifukofuko vilipo tayari kufuatilia mavuno, kuishi, na ubora.",
    "Record harvest": "Rekodi mavuno",
    "Avg weight": "Uzito wastani",
    "Yield/100 eggs": "Mavuno/mayai 100",
    "Cocoons": "Vifukofuko",
    "Total weight": "Uzito jumla",
    "Survival": "Kuishi",
    "Survival Rate": "Kiwango cha kuishi",
    "Record harvest weight, count, and shell samples.": "Rekodi uzito, idadi, na sampuli za ganda.",
    "Start a rearing cycle to record harvests.": "Anza mzunguko kurekodi mavuno.",
    "Start a rearing cycle to log feeding.": "Anza mzunguko kurekodi chakula.",
    "Start a rearing cycle to log health records.": "Anza mzunguko kurekodi afya.",
    "Log daily feed type and quantity per batch.": "Rekodi aina ya chakula na kiasi kwa kila kundi.",
    "Record losses, disease, and treatment.": "Rekodi hasara, magonjwa, na matibabu.",
    "Delete record?": "Futa rekodi?",
    "Delete": "Futa",
    "feeding log": "rekodi ya chakula",
    "mortality log": "rekodi ya vifo",
    "environment reading": "kipimo cha mazingira",
    "harvest record": "rekodi ya mavuno",
    "Harvest record": "Rekodi ya mavuno",
    # Leaf
    "Leaf stock (kg)": "Majani (kg)",
    "Leaf inventory": "Mali ya majani",
    "Save leaf stock": "Hifadhi majani",
    "Mulberry (kg)": "Mforosadi (kg)",
    "Castor (kg)": "Mbarika (kg)",
    "Kesseru (kg)": "Kesseru (kg)",
    "Leaf needed to harvest": "Majani yanayohitajika hadi mavuno",
    "Bombyx Stock": "Hisa ya Bombyx",
    "Eri Stock": "Hisa ya Eri",
    "Bombyx Price": "Bei ya Bombyx",
    "Eri Price": "Bei ya Eri",
    "Enter a valid price": "Weka bei sahihi",
    "No batches in inventory": "Hakuna makundi kwenye mali",
    "Create a rearing batch to track Bombyx and Eri stock.": "Unda kundi kufuatilia hisa ya Bombyx na Eri.",
    # Finance / reports
    "Record Payment": "Rekodi malipo",
    "Track receivables, payables, and settlement history.": "Fuatilia mapato, madeni, na malipo.",
    "Total Receivable": "Jumla inayopokelewa",
    "Total Payable": "Jumla inayolipwa",
    "Pending Settlements": "Malipo yanayosubiri",
    "Recent Activity": "Shughuli za hivi karibuni",
    "No payments recorded yet": "Hakuna malipo yaliyorekodiwa",
    "Log cocoon sales, seed purchases, and other transactions.": "Rekodi mauzo ya vifukofuko, manunuzi ya mbegu, na malipo mengine.",
    "Mark settled": "Weka yamelipwa",
    "Purchase": "Nunua",
    "Find KALRO seed suppliers and rearing support.": "Tafuta wasambazaji wa mbegu wa KALRO na msaada wa ufugaji.",
    "Total Orders": "Jumla ya oda",
    "Total Spend": "Jumla ya matumizi",
    "Producers": "Wazalishaji",
    "Recent Purchases": "Manunuzi ya hivi karibuni",
    "No purchases yet": "Hakuna manunuzi bado",
    "Tap Purchase on a producer to log seed or chawki orders.": "Gusa Nunua kwenye mzalishaji kurekodi oda ya mbegu au chawki.",
    "Add Producer": "Ongeza mzalishaji",
    "Item": "Bidhaa",
    "Quantity": "Kiasi",
    "Unit": "Kipimo",
    "Required": "Inahitajika",
    "Enter quantity": "Weka kiasi",
    "Enter what you purchased": "Weka ulichonunua",
    "Enter a name": "Weka jina",
    "Amount (KSh, optional)": "Kiasi (KSh, si lazima)",
    "Creates a payable on Payments tab": "Inaunda deni kwenye Malipo",
    "Order date": "Tarehe ya oda",
    "Save purchase": "Hifadhi ununuzi",
    "DFL, eggs, chawki batch": "DFL, mayai, kundi la chawki",
    "Bombyx mori, Eri": "Bombyx mori, Eri",
    "Buyer, supplier, or center name": "Jina la mnunuzi, msambazaji, au kituo",
    "Cocoon sale, seed purchase, etc.": "Uuzaji wa vifukofuko, ununuzi wa mbegu, n.k.",
    "Feed Logged": "Chakula kilichorekodiwa",
    "Total Larvae": "Jumla ya mabuu",
    "Feed trend (14 days)": "Mwelekeo wa chakula (siku 14)",
    "Mortality trend (14 days)": "Mwelekeo wa vifo (siku 14)",
    "Live larvae by species": "Mabuu hai kwa aina",
    "Batch comparison": "Kulinganisha makundi",
    "Rearing": "Ufugaji",
    "Total batches": "Jumla ya makundi",
    "Bombyx larvae": "Mabuu ya Bombyx",
    "Eri larvae": "Mabuu ya Eri",
    "Total feed logged": "Jumla ya chakula",
    "Feed log entries": "Nyingizo za chakula",
    "Health & harvest": "Afya na mavuno",
    "Total mortality": "Jumla ya vifo",
    "Average survival": "Wastani wa kuishi",
    "Harvest records": "Rekodi za mavuno",
    "Total cocoon weight": "Uzito jumla wa vifukofuko",
    "Export PDF report": "Hamisha ripoti ya PDF",
    "Export farm CSV to clipboard": "Nakili CSV ya shamba",
    "Export latest cycle CSV": "Nakili CSV ya mzunguko",
    "Export latest cycle PDF": "Hifadhi PDF ya mzunguko",
    "Export CSV to clipboard": "Nakili CSV",
    "Financial": "Fedha",
    "Pending receivable": "Yanayopokelewa",
    "Pending payable": "Yanayolipwa",
    "Purchase spend": "Matumizi ya manunuzi",
    "Purchase orders": "Oda za manunuzi",
    "Settled payments": "Malipo yaliyokamilika",
    "Pending payments": "Malipo yanayosubiri",
    "Farm data copied to clipboard as CSV": "Data ya shamba imenakiliwa kama CSV",
    "No batches to export": "Hakuna makundi ya kuhamisha",
    "No active batches to compare": "Hakuna makundi ya kulinganisha",
    "No feed logged in the last 14 days": "Hakuna chakula katika siku 14",
    "No mortality recorded in the last 14 days": "Hakuna vifo katika siku 14",
    "No active larvae to display": "Hakuna mabuu hai ya kuonyesha",
    "None logged": "Hakuna kilichorekodiwa",
    # Profile
    "Edit Name": "Badilisha jina",
    "Total Cycles": "Mizunguko jumla",
    "Lifetime Yield": "Mavuno ya maisha",
    "Avg Survival": "Wastani wa kuishi",
    "My reminders": "Vikumbusho vyangu",
    "My Reminders": "Vikumbusho vyangu",
    "Data & Backup": "Data na nakala",
    "Data & backup": "Data na nakala",
    "Secure your data locally": "Hifadhi data yako salama",
    "Kalro Knowledge Base": "Maktaba ya Kalro",
    "Hatch, moult rest days, spinning signs": "Kutotoa, kuvua, ishara za kusokota",
    "Are you sure you want to log out?": "Una uhakika unataka kutoka?",
    "Backup Now": "Hifadhi sasa",
    "Data backed up securely!": "Data imehifadhiwa salama!",
    "Backed up safely.": "Imehifadhiwa salama.",
    # Reminders / sync / backup
    "Notification schedule": "Ratiba ya arifa",
    "Stay on top of feeding and lifecycle milestones.": "Kumbuka chakula na hatua za mzunguko.",
    "Enable reminders": "Washa vikumbusho",
    "Daily rearing reminder": "Kikumbusho cha ufugaji wa kila siku",
    "Daily feeding reminder": "Kikumbusho cha chakula",
    "Milestone reminders": "Vikumbusho vya hatua",
    "Hatch, moult, and harvest dates": "Kutotoa, kuvua, na mavuno",
    "Farm reminders": "Vikumbusho vya shamba",
    "Configure feeding and milestone alerts": "Panga arifa za chakula na hatua",
    "Push notifications work on Android and iOS. On this device, use Home tab alerts instead.": "Arifa za simu zinafanya kazi Android na iOS. Kwenye kifaa hiki, tumia arifa za Leo.",
    "Download cloud data?": "Pakua data ya wingu?",
    "This replaces local farm data with the cloud snapshot. Continue?": "Hii inachukua nafasi ya data ya shamba kwa nakala ya wingu. Endelea?",
    "Newer data on this phone": "Data mpya kwenye simu hii",
    "This phone already uploaded a newer snapshot. Replace it with the cloud copy?": "Simu hii tayari ilipakia nakala mpya. Ibadilishe na ya wingu?",
    "Sync code copied": "Msimbo wa usawazishaji umenakiliwa",
    "Sync history": "Historia ya wingu",
    "Cloud sync": "Usawazishaji wa wingu",
    "Cloud Sync": "Usawazishaji wa wingu",
    "Farm sync code": "Msimbo wa shamba",
    "Share this code with team devices on your farm.": "Shiriki msimbo huu na vifaa vya timu shambani.",
    "Sync server": "Seva ya usawazishaji",
    "Server URL": "Anwani ya seva",
    "Optional HTTP endpoint for multi-device sync.": "Anwani ya HTTP kwa vifaa vingi (si lazima).",
    "Uploaded": "Imepakiwa",
    "Downloaded": "Imepakuliwa",
    "Not synced": "Haijasawazishwa",
    "Data encrypted and synced": "Data imesimbwa na kusawazishwa",
    "Uploading...": "Inapakia...",
    "Downloading...": "Inapakua...",
    "Upload to cloud": "Pakia wingu",
    "Download from cloud": "Pakua kutoka wingu",
    "Restore backup?": "Rejesha nakala?",
    "This replaces all local farm data with the backup file. Continue?": "Hii inachukua nafasi ya data yote ya shamba. Endelea?",
    "Backup restored successfully": "Nakala imerejeshwa",
    "Restore from backup": "Rejesha kutoka nakala",
    "Full farm backup": "Nakala kamili ya shamba",
    "Export batches, logs, payments, inventory, and settings as JSON.": "Hamisha makundi, rekodi, malipo, mali, na mipangilio kama JSON.",
    "Export backup (JSON)": "Hamisha nakala (JSON)",
    "Export or restore full farm JSON": "Hamisha au rejesha JSON ya shamba",
    "Backups are saved to your Documents/kalro_exports folder.": "Nakala zinahifadhiwa kwenye Documents/kalro_exports.",
    "Admin access required to restore backups": "Unahitaji ufikiaji wa msimamizi kurejesha nakala",
    "Admin access required": "Ufikiaji wa msimamizi unahitajika",
    "Admin access only": "Ufikiaji wa msimamizi pekee",
    "Farm settings": "Mipangilio ya shamba",
    "Farm settings saved": "Mipangilio ya shamba imehifadhiwa",
    "Save changes": "Hifadhi mabadiliko",
    "This name appears on your profile and exports.": "Jina hili linaonekana kwenye profaili na faili zinazohamishwa.",
    "Farm details": "Maelezo ya shamba",
    "Organization name and farm metadata": "Jina la shirika na maelezo ya shamba",
    "e.g. Kalro Sericulture Farm": "mf. Shamba la Kalro",
    "Farm management": "Usimamizi wa shamba",
    "Farm management is for administrators. Use My farm work for daily rearing tasks.": "Usimamizi ni kwa wasimamizi. Tumia kazi ya kila siku kwa ufugaji.",
    "Management tools control users, backups, and farm-wide settings. Field workers use a separate sign-in.": "Zana za usimamizi zinadhibiti watumiaji, nakala, na mipangilio. Wafanyakazi wa shamba wanaingia tofauti.",
    "Team members": "Wanakikundi",
    "Team users": "Watumiaji wa timu",
    "Add user": "Ongeza mtumiaji",
    "Add team member": "Ongeza mwanakikundi",
    "Add caretakers or viewers to share farm access.": "Ongeza wahudumu au watazamaji kushiriki ufikiaji.",
    "No team members yet": "Hakuna wanakikundi bado",
    "Reset PIN": "Weka PIN mpya",
    "Change role": "Badilisha wajibu",
    "Remove user": "Ondoa mtumiaji",
    "This deactivates the account. They will no longer be able to sign in.": "Hii inazima akaunti. Hataweza kuingia tena.",
    "New PIN": "PIN mpya",
    "Display name": "Jina linaloonekana",
    "Role": "Wajibu",
    "Sync & Backup": "Hifadhi nakala",
    "Export farm data or sync with team.": "Hamisha data au sawazisha na timu.",
    "Manage organization profile and roles.": "Dhibiti shirika na majukumu.",
    "Data & systems": "Data na mifumo",
    "Backups, cloud sync, and farm-wide notifications": "Nakala, wingu, na arifa za shamba",
    "Farm identity and user access": "Utambulisho wa shamba na ufikiaji",
    "Operations overview": "Muhtasari wa shughuli",
    "Farm health, team, and financial activity": "Afya ya shamba, timu, na fedha",
    "Charts, CSV, and PDF for farm records": "Chati, CSV, na PDF za rekodi",
    "Reports & exports": "Ripoti na uhamishaji",
    "Financial and production reports": "Ripoti za fedha na uzalishaji",
    "My farm work": "Kazi yangu ya shamba",
    "My work": "Kazi yangu",
    "Today on the farm": "Leo shambani",
    "Tasks and alerts that need your attention": "Kazi na arifa zinazohitaji uangalizi",
    "Tasks, alerts, and batch overview": "Kazi, arifa, na muhtasari wa kundi",
    "Batches & inventory": "Makundi na mali",
    "View larvae stock and batch details": "Tazama mabuu na maelezo ya kundi",
    "Reports, reminders, and field support": "Ripoti, vikumbusho, na msaada",
    "Feed trends, harvest, and batch comparison": "Mwelekeo wa chakula, mavuno, na kulinganisha",
    "Field guides": "Miongozo ya shamba",
    "Farm operations": "Shughuli za shamba",
    "My rearing snapshot": "Muhtasari wangu",
    "Farm management hub": "Kituo cha usimamizi",
    "Field operations": "Kazi za shamba",
    "Daily rearing, feeding, and batch work": "Ufugaji, chakula, na kazi za kundi",
    "Team, finance, backups, and farm settings": "Timu, fedha, nakala, na mipangilio",
    # Field guide
    "From KALRO predictive rearing sheets": "Kutoka karatasi za KALRO za ufugaji",
    "Bombyx — day of cycle": "Bombyx — siku ya mzunguko",
    "Days 1–12: incubate eggs, watch temperature and humidity, prepare the room.": "Siku 1–12: luza mayai, angalia joto na unyevu, andaa chumba.",
    "Days 10–12: hatching and brushing onto the rearing bed.": "Siku 10–12: kutotoa na kuhamisha kwenye kitanda.",
    "Each instar: feed, hygiene, spacing, disease watch.": "Kila kipindi: chakula, usafi, nafasi, magonjwa.",
    "Moult days 14, 18, 22, 26: stop feeding and watch the moult.": "Siku za kuvua 14, 18, 22, 26: acha kulisha na angalia kuvua.",
    "Days 27–33: heavy feeding. Days 32–35: stop feed and mount.": "Siku 27–33: chakula kingi. Siku 32–35: acha chakula na pandisha.",
    "Harvest mature cocoons on days 38–40.": "Vuna vifukofuko vilivyoiva siku 38–40.",
    "They stop eating and ignore fresh mulberry.": "Wanaacha kula na hawajali mforosadi mpya.",
    "They stop eating and ignore fresh leaf": "Wanaacha kula na hawajali majani mapya",
    "Body looks translucent or creamy around the head.": "Mwili unaonekana wazi au rangi ya maziwa kichwani.",
    "Body looks translucent or creamy around the head": "Mwili unaonekana wazi au rangi ya maziwa kichwani",
    "Body is softer and slightly shrunken.": "Mwili ni laini na umepungua kidogo.",
    "Body is softer and slightly shrunken": "Mwili ni laini na umepungua kidogo",
    "They raise and wave the head, searching for a place to attach silk.": "Wanainua na kutikisa kichwa wakitafuta mahali pa silk.",
    "They raise and wave the head, searching for a place to attach silk": "Wanainua na kutikisa kichwa wakitafuta mahali pa silk",
    "Eri — from hatch": "Eri — tangu kutotoa",
    "Instar day 1 (2nd–5th): light feeding in the morning, then full.": "Siku 1 ya kipindi (2–5): chakula kidogo asubuhi, kisha kamili.",
    "Last day of instars 1–4: no feeding (moult).": "Siku ya mwisho ya vipindi 1–4: hakuna chakula (kuvua).",
    "5th instar: feed days 1–7, then spinning; keep feeding until all have spun.": "Kipindi cha 5: lisha siku 1–7, kisha kusokota; endelea kulisha hadi wote wamesokota.",
    "Cocoon measurements around day 32. Moths emerge from day 39 (1–4 days).": "Vipimo vya vifukofuko karibu siku 32. Nondo kutoka siku 39 (siku 1–4).",
    "Disease field cards": "Kadi za magonjwa",
    "Use these when logging deaths. Pebrine is a seed-lot risk — tell CRC.": "Tumia hizi unaporekodi vifo. Pebrine ni hatari ya mbegu — mwambie CRC.",
    # Disease
    "Grasserie (NPV)": "Grasserie (NPV)",
    "Shiny, swollen larvae; milky fluid if crushed. Often after crowding or heat.": "Mabuu yenye kung'aa, yamevimba; maji meupe yakisagwa. Mara nyingi baada ya msongamano au joto.",
    "Pick out sick worms immediately. Keep the bed dry and less crowded. Burn or bury the dead. Do not feed wet leaf.": "Toa wagonjwa mara moja. Kitanda kiwe kavu na nafasi. Choma au zika wafu. Usilishe majani maji.",
    "Flacherie (IFV)": "Flacherie (IFV)",
    "Soft, dark, foul-smelling larvae; they stop eating and hang limp.": "Mabuu laini, meusi, yenye harufu; wanaacha kula na hung'aa.",
    "Remove all sick and dead worms. Clean trays. Feed fresh, well-dried leaf. Reduce density.": "Toa wagonjwa na wafu. Safisha trei. Lisha majani mapya yaliyokauka. Punguza msongamano.",
    "Pebrine": "Pebrine",
    "Pepper-like black spots, slow growth, irregular moults. Can pass through eggs.": "Madoa meusi kama pilipili, ukuaji wa polepole, kuvua isivyo kawaida. Inaweza kupita kwenye mayai.",
    "Treat as a seed-lot risk. Isolate the batch. Tell CRC / seed producer. Do not use moths from this lot for eggs.": "Chukulia kama hatari ya mbegu. Tenga kundi. Mwambie CRC / mzalishaji. Usitumie nondo wa lundo hili kwa mayai.",
    "Muscardine": "Muscardine",
    "Larvae stiffen and later show white or green powder (fungus).": "Mabuu yanaganda kisha yana unga mweupe au kijani (kuvu).",
    "Remove mummies. Dry the house. Improve ventilation. Do not overcrowd wet beds.": "Toa maiti ngumu. Kauka nyumba. Boresha hewa. Usijaze vitanda vya maji.",
    "Bacterial wilt": "Kunyauka kwa bakteria",
    "Sudden collapse, watery body, bad smell.": "Kuanguka ghafla, mwili wa maji, harufu mbaya.",
    "Remove dead worms. Hygiene and dry leaf. Watch neighbouring trays.": "Toa wafu. Usafi na majani makavu. Angalia trei jirani.",
    "Unknown / other": "Haijulikani / nyingine",
    "Anything that is not on this list.": "Cho chote kisicho kwenye orodha hii.",
    "Isolate, photograph if you can, and ask CRC. Record count so live larvae stay honest.": "Tenga, piga picha ukiweza, uliza CRC. Rekodi idadi ili mabuu hai yawe sahihi.",
    # Lifecycle actions
    "Incubate eggs. Watch temperature and humidity. Prepare the rearing room.": "Luza mayai. Angalia joto na unyevu. Andaa chumba.",
    "Feed tender chopped mulberry. Keep density low. Brush newly hatched larvae onto the bed.": "Lisha mforosadi laini uliokatwa. Nafasi iwe kubwa. Hamisha mabuu mapya kwenye kitanda.",
    "Stop feeding. Watch the first moult.": "Acha kulisha. Angalia kuvua kwa kwanza.",
    "Feed, clean the bed, and watch for disease.": "Lisha, safisha kitanda, angalia magonjwa.",
    "Stop feeding. Observe the second moult.": "Acha kulisha. Angalia kuvua kwa pili.",
    "Increase feeding, give more space, keep the bed clean.": "Ongeza chakula, ongeza nafasi, kitanda kiwe safi.",
    "Stop feeding. Observe the third moult.": "Acha kulisha. Angalia kuvua kwa tatu.",
    "Heavy feeding, bed cleaning, and spacing. Leaf demand rises.": "Chakula kingi, usafi, na nafasi. Mahitaji ya majani yanaongezeka.",
    "Stop feeding. Prepare for the final instar.": "Acha kulisha. Andaa kipindi cha mwisho.",
    "Peak feeding and growth. Prepare mountages.": "Chakula cha kilele na ukuaji. Andaa mountages.",
    "Stop feeding. Place worms on mountages. Keep the house quiet.": "Acha kulisha. Weka minyoo kwenye mountages. Nyumba iwe kimya.",
    "Cocoon spinning. Dim light, stable temperature, do not disturb.": "Kusokota. Mwanga hafifu, joto thabiti, usisumbue.",
    "Harvest mature cocoons in this window. Sort defectives and record weight.": "Vuna vifukofuko vilivyoiva katika dirisha hili. Tenga vilivyo na kasoro na rekodi uzito.",
    "Moths emerge. For seed: pairing trays. For silk: harvest before this date.": "Nondo wanatoka. Kwa mbegu: trei za kuoanisha. Kwa hariri: vuna kabla ya tarehe hii.",
    "Incubate eggs. Prepare tender castor or kesseru leaf.": "Luza mayai. Andaa majani laini ya mbarika au kesseru.",
    "Feed tender leaf. Keep young larvae warm and uncrowded.": "Lisha majani laini. Mabuu machanga yawe na joto na nafasi.",
    "No feeding today — 1st moult.": "Hakuna chakula leo — kuvua 1.",
    "Day 1: light feeding in the morning, then full. Other days: full feeding.": "Siku 1: chakula kidogo asubuhi, kisha kamili. Siku nyingine: kamili.",
    "No feeding today — 2nd moult.": "Hakuna chakula leo — kuvua 2.",
    "Day 1: light morning feed, then full. Then feed normally until the moult.": "Siku 1: kidogo asubuhi kisha kamili. Kisha lisha kawaida hadi kuvua.",
    "No feeding today — 3rd moult.": "Hakuna chakula leo — kuvua 3.",
    "Day 1 light then full. Leaf demand is rising.": "Siku 1 kidogo kisha kamili. Mahitaji ya majani yanaongezeka.",
    "No feeding today — 4th moult. Prepare for the final instar.": "Hakuna chakula leo — kuvua 4. Andaa kipindi cha mwisho.",
    "Peak feeding on castor or kesseru. Prepare quiet spinning sites.": "Chakula cha kilele cha mbarika au kesseru. Andaa sehemu tulivu za kusokota.",
    "Spinning. Keep feeding until every larva has spun.": "Kusokota. Endelea kulisha hadi kila buu limesokota.",
    "Cocoon measurements and harvest. Record count and weight.": "Vipimo na mavuno ya vifukofuko. Rekodi idadi na uzito.",
    "Moth emergence and egg laying. Prepare pairing trays for seed.": "Kutoka kwa nondo na kuweka mayai. Andaa trei za kuoanisha mbegu.",
    "Eggs are hatching. Transfer / brush larvae onto the rearing bed. Prepare tender leaf.": "Mayai yanatotoa. Hamisha mabuu kwenye kitanda. Andaa majani laini.",
    "Observe hatching and brush larvae onto the rearing bed. Feed tender chopped leaf.": "Angalia kutotoa na hamisha mabuu kwenye kitanda. Lisha majani laini yaliyokatwa.",
    "Feeding decreases sharply or stops": "Kula kunapungua ghafla au kusimama",
    "Movement decreases; larvae stay still": "Harakati zinapungua; mabuu yanakaa kimya",
    "Body may look swollen or dull": "Mwili unaweza kuvimba au kufifia",
    "Many larvae change together": "Mabuu mengi yanabadilika pamoja",
    "10–12 days": "Siku 10–12",
    "3 days feeding": "Siku 3 za chakula",
    "1 rest day": "Siku 1 ya pumziko",
    "6–7 days": "Siku 6–7",
    "1 day": "Siku 1",
    "3–5 days": "Siku 3–5",
    "Day 38–40": "Siku 38–40",
    "12–16 days": "Siku 12–16",
    "10 days": "Siku 10",
    "2 days feeding": "Siku 2 za chakula",
    "5 days feeding": "Siku 5 za chakula",
    "7 days feeding": "Siku 7 za chakula",
    "3 days": "Siku 3",
    "Day 32 from hatch": "Siku 32 tangu kutotoa",
    "1–4 days emergence": "Kutoka kwa siku 1–4",
    # Misc UI leftovers
    "Excellent": "Nzuri sana",
    "Estimated cocoon": "Kadirio la vifukofuko",
    "Expected Yield": "Mavuno yaliyotarajiwa",
    "Plan and track rearing cycles": "Panga na fuatilia mizunguko",
    "Create batches and follow each cycle from egg to harvest.": "Unda makundi na fuata kila mzunguko kutoka mayai hadi mavuno.",
    "Predict lifecycle dates": "Tabiri tarehe za mzunguko",
    "Hatch, harvest, and moth dates that move with weather and how much leaf you give.": "Tarehe za kutotoa, mavuno, na nondo zinazohama na hewa na majani.",
    "Record feeding schedules": "Rekodi ratiba ya chakula",
    "Monitor larval growth stages": "Fuatilia hatua za ukuaji wa mabuu",
    "Mark observed instars to keep predictions accurate.": "Weka vipindi ulivyoona ili utabiri uwe sahihi.",
    "Record mortality and disease": "Rekodi vifo na magonjwa",
    "Track losses, disease, treatment, and environment stress.": "Fuatilia hasara, magonjwa, matibabu, na msongo wa mazingira.",
    "Analyze cocoon quality and yield": "Changanua ubora na mavuno ya vifukofuko",
    "Compare batch performance": "Linganisha utendaji wa makundi",
    "Survival, feed use, and side-by-side batch charts.": "Kuishi, chakula, na chati za makundi.",
    "Productivity and profitability reports": "Ripoti za uzalishaji na faida",
    "Export CSV and PDF for farm records and finance.": "Hamisha CSV na PDF za rekodi na fedha.",
    "Hatch, moult rest days, harvest window, moths.": "Kutotoa, kuvua, dirisha la mavuno, nondo.",
    "See hatch, moult rest days, spinning, and the cocoon harvest window before you start eggs.": "Ona kutotoa, kuvua, kusokota, na dirisha la mavuno kabla ya kuanza mayai.",
    "Something went wrong": "Hitilafu imetokea",
    "No cloud snapshot found for this sync code": "Hakuna nakala ya wingu kwa msimbo huu",
    "Uploaded to cloud successfully": "Imepakiwa wingu kikamilifu",
    "Cloud data downloaded and applied": "Data ya wingu imepakuliwa na kutumika",
    "This phone already uploaded a newer snapshot. Download anyway only if you mean to replace it.": "Simu hii ilipakia nakala mpya. Pakua tena tu ukitaka kubadilisha.",
    "Daily rearing check": "Ukaguzi wa ufugaji wa kila siku",
    "Open Kalro to log feed, house, and deaths.": "Fungua Kalro kurekodi chakula, nyumba, na vifo.",
    "Expected today. Open Kalro to mark it if you see it.": "Inatarajiwa leo. Fungua Kalro kuiweka alama ukiona.",
    "Keep feeding until all have spun · ~{g} g": "Endelea kulisha hadi wote wamesokota · ~{g} g",
    "Light morning feed, then full · ~{g} g": "Chakula kidogo asubuhi, kisha kamili · ~{g} g",
    "Full ration · ~{g} g": "Kiasi kamili · ~{g} g",
    "About": "Takriban",
    "kg leaf still needed to harvest": "kg za majani bado zinahitajika hadi mavuno",
    "Open the farm": "Fungua shamba",
    "vs typical": "dhidi ya kawaida",
    "of need": "ya mahitaji",
    "leaf": "majani",
    "today’s feed, rest, or harvest": "chakula, pumziko, au mavuno ya leo",
    "Humidity out of range": "Unyevu nje ya kiwango",
    "Light then full feed": "Chakula kidogo kisha kamili",
    "Record mortality check": "Rekodi ukaguzi wa vifo",
    "Wrong username or PIN.": "Jina la kuingia au PIN si sahihi.",
    "No farm account is available yet.": "Akaunti ya shamba bado haipatikani.",
    "Complete app setup first.": "Kamilisha usanidi kwanza.",
    "PIN": "PIN",
    "Sign in": "Ingia",
    "today": "leo",
    "overdue": "imepita",
    "Today": "Leo",
    "Overdue": "Imepita",
    "Tomorrow": "Kesho",
    "Starting": "Inaanza",
    "Rest": "Pumziko",
    "Update": "Sasisha",
    "Mark": "Weka",
    "OK": "Sawa",
    "Dry": "Kavu",
    "Wet": "Majivu",
    "Logged so far": "Iliyorekodiwa hadi sasa",
    "Pre-moult signs": "Ishara za kuvua",
    "Ready to spin?": "Tayari kusokota?",
    "I see this — mark today": "Naona hivi — weka leo",
    "Export PDF report": "Hamisha ripoti ya PDF",
    "See hatch, harvest, and moth dates. Test cool weather, heat, or short leaf.": "Ona kutotoa, mavuno, na nondo. Jaribu baridi, joto, au majani machache.",
    "Egg hatch": "Mayai kutotoa",
    "1st instar feeding": "Kulisha kipindi cha 1",
    "1st moult — stop feeding": "Kuvua 1 — acha kulisha",
    "2nd instar feeding": "Kulisha kipindi cha 2",
    "2nd moult — stop feeding": "Kuvua 2 — acha kulisha",
    "3rd instar feeding": "Kulisha kipindi cha 3",
    "3rd moult — stop feeding": "Kuvua 3 — acha kulisha",
    "4th instar feeding": "Kulisha kipindi cha 4",
    "4th moult — stop feeding": "Kuvua 4 — acha kulisha",
    "Mature larvae (5th instar)": "Mabuu makubwa (kipindi cha 5)",
    "Cocoon harvest window": "Dirisha la mavuno ya vifukofuko",
    "Moth emergence (cocoons hatch)": "Nondo kutoka (vifukofuko)",
    "10–12 days": "siku 10–12",
    "3 days feeding": "siku 3 za chakula",
    "1 rest day": "siku 1 ya pumziko",
    "6–7 days": "siku 6–7",
    "1 day": "siku 1",
    "3–5 days": "siku 3–5",
    "Day 38–40": "Siku 38–40",
    "12–16 days": "siku 12–16",
    "10 days": "siku 10",
    "2 days feeding": "siku 2 za chakula",
    "5 days feeding": "siku 5 za chakula",
    "7 days feeding": "siku 7 za chakula",
    "3 days": "siku 3",
    "Day 32 from hatch": "Siku 32 baada ya kutotoa",
    "1–4 days emergence": "siku 1–4 za kutoka",
    "Feed often. Keep density low. Watch for the first moult.": "Lisha mara nyingi. Weka nafasi. Angalia kuvua kwa kwanza.",
    "Stop feeding. Watch the first moult, then resume tender leaf.": "Acha kulisha. Angalia kuvua kwa kwanza, kisha rudisha majani laini.",
    "Feed, clean the bed, and watch humidity and disease.": "Lisha, safisha kitanda, angalia unyevu na magonjwa.",
    "Give larvae more space; mulberry demand starts to rise.": "Wape mabuu nafasi; mahitaji ya mforosadi yanaongezeka.",
    "Give larvae more space; castor or kesseru demand starts to rise.": "Wape mabuu nafasi; mahitaji ya mbarika au kesseru yanaongezeka.",
    "Heavy feeding and spacing. Late instars eat most of the crop.": "Kulisha nyingi na nafasi. Vipindi vya mwisho hula majani mengi.",
    "Peak feeding. Watch spinning signs. Prepare mountages.": "Kulisha kilele. Angalia ishara za kusokota. Andaa mategemeo.",
    "Peak feeding on castor or kesseru. Day 1 is a light morning feed, then full.": "Kulisha kilele kwenye mbarika au kesseru. Siku 1 chakula kidogo asubuhi, kisha kamili.",
    "Stop feeding. Mount larvae on chandrika or mountages. Keep the house quiet.": "Acha kulisha. Weka mabuu kwenye mategemeo. Nyumba iwe kimya.",
    "Keep feeding until every larva has spun. Dim light, do not disturb.": "Endelea kulisha hadi kila buu imesokota. Mwanga hafifu, usisumbue.",
    "Eggs hatch. Brush larvae onto the bed. Prepare tender chopped mulberry leaf.": "Mayai yanatotoa. Hamisha mabuu kwenye kitanda. Andaa majani laini ya mforosadi.",
    "Eggs hatch. Brush larvae onto the bed. Prepare tender chopped castor or kesseru leaf.": "Mayai yanatotoa. Hamisha mabuu kwenye kitanda. Andaa majani laini ya mbarika au kesseru.",
    "Check spinning / moult signs": "Angalia ishara za kusokota / kuvua",
    "Harvest window": "Dirisha la mavuno",
    "High mortality today": "Vifo vingi leo",
    "No feeding logged today": "Hakuna chakula kilichorekodiwa leo",
    "Temperature out of range": "Joto nje ya kiwango",
    "Daily reminders": "Vikumbusho vya kila siku",
    "Daily sericulture task reminders": "Vikumbusho vya kazi za ufugaji hariri",
    "Milestone reminders": "Vikumbusho vya hatua",
    "Lifecycle milestone reminders": "Vikumbusho vya hatua za mzunguko",
    "Need {today} kg today · stock {stock} kg · tap Farm to update.": "Inahitaji {today} kg leo · akiba {stock} kg · gusa Shamba kusasisha.",
    "Need {today} kg today · stock {stock} kg · {remaining} kg still to harvest · tap Farm to update.": "Inahitaji {today} kg leo · akiba {stock} kg · {remaining} kg bado hadi mavuno · gusa Shamba kusasisha.",
    "day {d} of {n}": "siku {d} kati ya {n}",
    "in {n} days": "baada ya siku {n}",
    "In {n} days": "Baada ya siku {n}",
    "Feed {g} g": "Lisha {g} g",
    "Stop feeding — {stage}": "Acha kulisha — {stage}",
    "Feed {species}": "Lisha {species}",
    "Feed {species} batch": "Lisha kundi la {species}",
    "Suggested ~{g}g for {n} larvae": "Inapendekezwa ~{g}g kwa mabuu {n}",
    "Overdue — {species}": "Imepita — {species}",
    "Expected today — {species}": "Inatarajiwa leo — {species}",
    "Expected tomorrow — {species}": "Inatarajiwa kesho — {species}",
    "{species} batch daily count": "Hesabu ya kila siku ya kundi la {species}",
    "{species} cocoons · {range}": "Vifukofuko vya {species} · {range}",
    "Logged vs {amount} suggested": "Iliyorekodiwa dhidi ya {amount} inayopendekezwa",
    "{n} records": "rekodi {n}",
    "{n} batches": "makundi {n}",
    "{n} in progress": "{n} yanaendelea",
    "Generated {datetime}": "Imetengenezwa {datetime}",
    "Sync code {code}": "Msimbo wa usawazishaji {code}",
    "Low survival — {species}": "Kuishi chini — {species}",
    "{pct}% survival ({live} live of {start}).": "Kuishi {pct}% ({live} hai kati ya {start}).",
    "{n} larvae lost today ({pct}% of batch).": "Mabuu {n} yamepotea leo ({pct}% ya kundi).",
    "{temp}°C recorded (ideal {min}–{max}°C).": "{temp}°C imerekodiwa (bora {min}–{max}°C).",
    "{pct}% humidity (ideal {min}–{max}%).": "Unyevu {pct}% (bora {min}–{max}%).",
    "{species} batch at {stage}.": "Kundi la {species} katika {stage}.",
    "I see this — mark {stage} today": "Naona hivi — weka {stage} leo",
    "Next {label} {date}": "Ifuatayo {label} {date}",
    "Day {n}": "Siku {n}",
    "Observed {date}": "Imeonekana {date}",
    "+{n}d vs typical": "+{n}s dhidi ya kawaida",
    "{n}d vs typical": "{n}s dhidi ya kawaida",
    "+{n}d with this weather / feeding": "+{n}s kwa hali hii ya hewa / chakula",
    "{n}d with this weather / feeding": "{n}s kwa hali hii ya hewa / chakula",
    "Today's tasks": "Kazi za leo",
    "Edit Name": "Badilisha jina",
    "Total Cycles": "Mizunguko",
    "Lifetime Yield": "Mavuno (kilo)",
    "Avg Survival": "Kiwango cha kuishi",
    "Language": "Lugha",
    "English": "Kiingereza",
    "Swahili": "Kiswahili",
    "My reminders": "Vikumbusho vyangu",
    "Data & Backup": "Data na nakala",
    "Secure your data locally": "Hifadhi data yako hapa",
    "Kalro Knowledge Base": "Maktaba ya Kalro",
    "Sign out": "Ondoka",
    "You": "Wewe",
    "in progress": "yanaendelea",
    "archived": "yaliyohifadhiwa",
    "Day {d} / {n}": "Siku {d} / {n}",
    "Started": "Imeanza",
    "Create": "Unda",
    "Harvest window. Pick mature cocoons over these days for silk quality.": "Dirisha la mavuno. Chukua vifukofuko vilivyoiva siku hizi kwa ubora wa hariri.",
    "Cocoon measurements and harvest. Sort defectives and record weight.": "Vipimo vya vifukofuko na mavuno. Tenga vilivyo na kasoro na rekodi uzito.",
    "Moths emerge. For seed: prepare pairing trays. For silk: harvest before this date.": "Nondo wanatoka. Kwa mbegu: andaa trei za kuoanisha. Kwa hariri: vuna kabla ya tarehe hii.",
    "Check the batch and mark the stage when you observe it.": "Angalia kundi na uweke hatua unapoiona.",
    "All": "Zote",
    "{n} days": "Siku {n}",
    "Start next lot like this": "Anza kundi linalofuata kama hili",
    "Send to CRC": "Tuma kwa CRC",
    "No cloud backup yet": "Bado hakuna nakala ya wingu",
    "Last backup {date}": "Nakala ya mwisho {date}",
    "Search name, house, caretaker": "Tafuta jina, nyumba, mlezi",
    "No lots match this filter": "Hakuna makundi yanayolingana na kichujio hiki",
    "Try All, another species, or clear the search.": "Jaribu Zote, aina nyingine, au futa utafutaji.",
    "This week": "Wiki hii",
    "This month": "Mwezi huu",
    "Harvest, survival, and cost per kg": "Mavuno, kuishi, na gharama kwa kilo",
    "Egg source (seed producer / CRC)": "Chanzo cha mayai (mzalishaji wa mbegu / CRC)",
    "Other / type below": "Nyingine / andika chini",
    "Disease photos": "Picha za magonjwa",
    "Leaf in / out": "Majani kuingia / kutoka",
    "Add bought leaf": "Ongeza majani yaliyonunuliwa",
    "Add cut leaf": "Ongeza majani yaliyokatwa",
    "Bought": "Yamenunuliwa",
    "Cut": "Yamekatwa",
    "Cut / harvested": "Yamekatwa / kuvunwa",
    "Fed to worms": "Yamelishwa visuwak",
    "Stock adjust": "Kurekebisha hisa",
    "Log bought or cut leaf. Feeding deducts stock automatically.": "Rekodi majani yaliyonunuliwa au kukatwa. Kulisha hupunguza hisa kiotomatiki.",
    "Days of cover at today’s larvae": "Siku za kutosha kwa mabuu ya leo",
    "{n} days of cover at today’s feed": "Siku {n} za majani kwa chakula cha leo",
    "{n} days cover": "Siku {n} za kutosha",
    "{kg} kg stock": "Hisa {kg} kg",
    "House — last {n} days": "Nyumba — siku {n} zilizopita",
    "Too hot on {n} days — Plan dates will move.": "Joto mno siku {n} — tarehe za Mpango zitahama.",
    "Cool · OK · hot from logged house chips.": "Baridi · sawa · moto kutoka kwenye rekodi za nyumba.",
    "Field guide for this stage": "Mwongozo wa hatua hii",
    "No harvest": "Hakuna mavuno",
    "{pct}% survival": "Kuishi {pct}%",
    "{kg} kg leaf": "Majani {kg} kg",
    "{n}d later than predicted": "Siku {n} baadaye kuliko ilivyotabiriwa",
    "{n}d earlier than predicted": "Siku {n} mapema kuliko ilivyotabiriwa",
    "Cost {cost} / kg cocoons": "Gharama {cost} / kg vifukofuko",
    "This batch": "Kundi hili",
    "All lots": "Makundi yote",
    "Feed trend ({n} days)": "Mwelekeo wa chakula (siku {n})",
    "Mortality trend ({n} days)": "Mwelekeo wa vifo (siku {n})",
    "{n} larvae lost": "Mabuu {n} yamekufa",
    "Record losses, disease photos, and house conditions.": "Rekodi hasara, picha za magonjwa, na hali ya nyumba.",
    "You will see feed or rest, live larvae, and one-tap Feed / Deaths / House for every batch.": "Utaona chakula au pumziko, mabuu hai, na Feed / Vifo / Nyumba kwa kila kundi.",
    "This is Today once a batch is running": "Hii ndiyo Leo kundi linapoanza",
    "Rest": "Pumziko",
    "Mix": "Mchanganyiko",
    "Needs feed": "Inahitaji chakula",
    "Fed today": "Imelishwa leo",
    "Rest day": "Siku ya pumziko",
    "Logged vs suggested today": "Iliyorekodiwa dhidi ya iliyopendekezwa leo",
    "Deaths logged today": "Vifo vilivyorekodiwa leo",
    "Harvest window open": "Dirisha la mavuno liko wazi",
    "Last recorded weight": "Uzito wa mwisho",
    "Open": "Wazi",
    "Coming up": "Zinazokuja",
    "Tomorrow": "Kesho",
    "Overdue": "Zimechelewa",
    "Kilograms": "Kilogramu",
    "Leaf type": "Aina ya majani",
    "Notes (optional)": "Maelezo (si lazima)",
    "{n} live": "{n} hai",
    "day {d} of {n}": "siku {d} kati ya {n}",
    "Manual stock edit": "Kuhariri hisa kwa mkono",
}

PREFIXES = {
    "Could not save batch: ": "Haikuweza kuhifadhi kundi: ",
    "Could not save purchase: ": "Haikuweza kuhifadhi ununuzi: ",
    "Could not save producer: ": "Haikuweza kuhifadhi mzalishaji: ",
    "Could not save payment: ": "Haikuweza kuhifadhi malipo: ",
    "Backup saved to ": "Nakala imehifadhiwa katika ",
    "Backup failed: ": "Nakala imeshindwa: ",
    "Restore failed: ": "Kurudisha kumeshindwa: ",
    "Save failed: ": "Kuhifadhi kumeshindwa: ",
    "Setup failed: ": "Usanidi umeshindwa: ",
    "PDF export failed: ": "Kuhamisha PDF kumeshindwa: ",
    "PDF saved to ": "PDF imehifadhiwa katika ",
    "Cycle PDF saved to ": "PDF ya mzunguko imehifadhiwa katika ",
    "Could not prepare farm account: ": "Haikuweza kuandaa akaunti ya shamba: ",
    "Create a batch first to ": "Unda kundi kwanza ili ",
    "Remove this ": "Ondoa ",
    "Treatment: ": "Matibabu: ",
    "Outside ideal range for ": "Nje ya kiwango kwa ",
    "Purchase from ": "Nunua kutoka ",
    "Reset PIN for ": "Weka PIN mpya kwa ",
    "Change role for ": "Badilisha wajibu wa ",
    "Cycle CSV copied (": "CSV ya mzunguko imenakiliwa (",
    "Something went wrong: ": "Hitilafu imetokea: ",
    "Remote upload failed (": "Kupakia kumeshindwa (",
    "Remote download failed (": "Kupakua kumeshindwa (",
    "Upload failed: ": "Kupakia kumeshindwa: ",
    "Download failed: ": "Kupakua kumeshindwa: ",
    "Uploaded to local cloud folder for sync code ": "Imepakiwa folda ya wingu kwa msimbo ",
    "Keep feeding until all have spun · ~": "Endelea kulisha hadi wote wamesokota · ~",
    "Light morning feed, then full · ~": "Chakula kidogo asubuhi, kisha kamili · ~",
    "Full ration · ~": "Kiasi kamili · ~",
    "Logged vs ": "Iliyorekodiwa dhidi ya ",
    "Harvest ~": "Mavuno ~",
    "Started ": "Imeanza ",
    "Good morning, ": "Habari za asubuhi, ",
    "Good afternoon, ": "Habari za mchana, ",
    "Good evening, ": "Habari za jioni, ",
    "Typically ": "Kwa kawaida ",
    "Observed ": "Imeonekana ",
    "Stop feeding — ": "Acha kulisha — ",
    "Expected today — ": "Inatarajiwa leo — ",
    "Expected tomorrow — ": "Inatarajiwa kesho — ",
    "Overdue — ": "Imepita — ",
    "Low survival — ": "Kuishi chini — ",
    "I see this — mark ": "Naona hivi — weka ",
    "Generated ": "Imetengenezwa ",
    "Sync code ": "Msimbo wa usawazishaji ",
}

SUFFIXES = {
    " larvae": " mabuu",
    " records": " rekodi",
    " batches": " makundi",
    "d vs typical": "s dhidi ya kawaida",
    "d with this weather / feeding": "s kwa hali hii ya hewa / chakula",
}


def dart_str(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def main() -> None:
    lines = [
        "// Generated by tool/generate_swahili.py — do not edit by hand.",
        "const swahiliMessages = <String, String>{",
    ]
    for k, v in sorted(MESSAGES.items(), key=lambda kv: kv[0].lower()):
        lines.append(f"  {dart_str(k)}: {dart_str(v)},")
    lines.append("};")
    lines.append("")
    lines.append("const swahiliPrefixes = <String, String>{")
    for k, v in sorted(PREFIXES.items(), key=lambda kv: -len(kv[0])):
        lines.append(f"  {dart_str(k)}: {dart_str(v)},")
    lines.append("};")
    lines.append("")
    lines.append("const swahiliSuffixes = <String, String>{")
    for k, v in sorted(SUFFIXES.items(), key=lambda kv: -len(kv[0])):
        lines.append(f"  {dart_str(k)}: {dart_str(v)},")
    lines.append("};")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(MESSAGES)} messages, {len(PREFIXES)} prefixes, {len(SUFFIXES)} suffixes)")


if __name__ == "__main__":
    main()
